language: node_js

notifications:
  email: false

install: yarn

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
    - stage: build
      script: yarn build
    - stage: release
      deploy:
        provider: script
        script: yarn release
        on:
          branch: 'stable'
